import { Download, FileText, FileJson } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface ExportSoilDataProps {
  data: {
    ph: number;
    organic_carbon: number;
    nitrogen: number;
    clay: number;
    sand: number;
    silt: number;
  };
  locationName: string;
}

const ExportSoilData = ({ data, locationName }: ExportSoilDataProps) => {
  const exportAsText = () => {
    const content = `
SOIL ANALYSIS REPORT
Location: ${locationName}
Date: ${new Date().toLocaleDateString()}

═══════════════════════════════════════

SOIL PROPERTIES:
  • pH Level: ${data.ph.toFixed(1)}
  • Organic Carbon: ${data.organic_carbon.toFixed(1)}%
  • Nitrogen: ${data.nitrogen.toFixed(2)} g/kg
  
SOIL TEXTURE:
  • Clay: ${data.clay.toFixed(1)}%
  • Sand: ${data.sand.toFixed(1)}%
  • Silt: ${data.silt.toFixed(1)}%

═══════════════════════════════════════
Report generated by SoilIntel
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `soil-report-${locationName.replace(/[^a-z0-9]/gi, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportAsJSON = () => {
    const jsonData = {
      location: locationName,
      date: new Date().toISOString(),
      soilProperties: {
        ph: data.ph,
        organicCarbon: data.organic_carbon,
        nitrogen: data.nitrogen,
        clay: data.clay,
        sand: data.sand,
        silt: data.silt,
      },
    };

    const blob = new Blob([JSON.stringify(jsonData, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `soil-data-${locationName.replace(/[^a-z0-9]/gi, "-")}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="w-4 h-4" />
          Export Report
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportAsText} className="gap-2">
          <FileText className="w-4 h-4" />
          Download as Text
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsJSON} className="gap-2">
          <FileJson className="w-4 h-4" />
          Download as JSON
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ExportSoilData;
